//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic1
    {
        public int Studid { get; set; }
        public string AcademicYrSemester { get; set; }
        public string Program1 { get; set; }
        public string GroupNumber { get; set; }
        public string GroupId11 { get; set; }
        public string SubGroupNo11 { get; set; }
        public string SubGroupId11 { get; set; }
    }
}
