//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class add_time_slot
    {
        public int Lec_id { get; set; }
        public string Batch_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time_slot { get; set; }
        public string start_time_hrs { get; set; }
        public string end_time_hrs { get; set; }
    }
}
