//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int LecID { get; set; }
        public string LectureName { get; set; }
        public string EmpID { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string Center { get; set; }
        public string Building { get; set; }
        public string Level { get; set; }
        public string Rank { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
    }
}
