//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture_tbl
    {
        public int lectID { get; set; }
        public string lectu_type { get; set; }
        public string lect_name { get; set; }
        public string subject { get; set; }
    }
}
