//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotAvTime
    {
        public int SessionID { get; set; }
        public string Selected_Lecturer { get; set; }
        public string Selected_group { get; set; }
        public string Selected_subgroup { get; set; }
        public string Selected_sessionId { get; set; }
        public string Time { get; set; }
    }
}
