//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomForGrSub
    {
        public int RsubGID { get; set; }
        public string stdG { get; set; }
        public string stdsubG { get; set; }
        public string roomNam { get; set; }
    }
}
