//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionN
    {
        public int SessionId { get; set; }
        public string Lecture1 { get; set; }
        public string Lecture2 { get; set; }
        public string Subject { get; set; }
        public string SubjectCode { get; set; }
        public string Tag { get; set; }
        public string GroupId { get; set; }
        public string NoOfStudents { get; set; }
        public string Duraction { get; set; }
    }
}
