//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject1
    {
        public int SID { get; set; }
        public string Year { get; set; }
        public string Semester { get; set; }
        public string Subject_Name { get; set; }
        public string Subject_Code { get; set; }
        public string Lecture_Hours { get; set; }
        public string Tute_Hours { get; set; }
        public string Lab_Hours { get; set; }
        public string Evaluation_Hours { get; set; }
    }
}
