//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace time_table
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_Day1
    {
        public int weekID { get; set; }
        public string MondayH { get; set; }
        public string MondayM { get; set; }
        public string tusedayH { get; set; }
        public string tusedayM { get; set; }
        public string wednesdayH { get; set; }
        public string wednesdayM { get; set; }
        public string thursdayH { get; set; }
        public string thursdayM { get; set; }
        public string fridayH { get; set; }
        public string fridayM { get; set; }
        public string saturdayH { get; set; }
        public string saturdayM { get; set; }
        public string sundayH { get; set; }
        public string sundayM { get; set; }
        public string num_of_working_days { get; set; }
    }
}
